language: php

sudo: false

php:
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: 7
    - php: 7.1
  fast_finish: true